services:
  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    network_mode: host

  scripts:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    env_file: ./backend/.env
    network_mode: host
    profiles:
      - pipeline

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "http://odiga-server.sandbox.seogyoung.com"
        VITE_KAKAO_MAP_KEY: ${VITE_KAKAO_MAP_KEY}
    restart: always
    ports:
      - "12000:12000"


volumes:
