services:
  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    network_mode: host

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "https://odiga-server.sandbox.seogyoung.com"
    restart: always
    ports:
      - "12000:12000"

